### ISSUE TITLE
Not an issue : Can't get this to work

### ISSUE THREAD

**Issue by saurabsalhotra** [AkiaCode/wasm-chika#1]
Hey this looks really interesting and I want to get this to work but am really unexperienced.

I tried installing the npm package i thought you need to import an init function from a pkg file.

Could you tell me how to make this work in the browser?

I cloned your repo and did a manual compile, then imported the wasm_chika.js into my index.js and it game me a chika object.

but the function names were chicka_clean and text_new.

I couldn't really do anything with them.

Point me in the right direction maybe.

sorry for being such a noob.

**Comment by AkiaCode** [comment]
Sorry to check late. First of all, I'm sorry that I didn't write an explanation of how to run it. 
@bombayblur, Please wait. I will come after writing the document

**Comment by AkiaCode** [comment]
Sorry, I wasn't good at publishing.

**Comment by AkiaCode** [comment]
Upgrade 0.1.1, Use https://www.npmjs.com/package/create-wasm-app and `npm i && npm i wasm-chika` and `npm run start` is starting work

Insert:
`index.js`
```
import * as Chika from "wasm-chika";

Chika.Chika.clean('chika')
new Chika.Text('chika', 'asd', 50, 50, 'bold 48px serif')
```

`index.html`
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello Chika!</title>
  </head>
  <body>
    <noscript>This page contains webassembly and javascript content, please enable javascript in your browser.</noscript>
    <script src="./bootstrap.js"></script>
    <canvas id="chika"></canvas>
  </body>
</html>
```

**Comment by AkiaCode** [comment]
And Sorry, there are not many canvas APIs supported yet
